version: '3.8'
services:

  database:
    image: mysql:8.0.39
    container_name: ${SERVICE_NAME}-database
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - "3306"

  flyway:
    image: flyway/flyway
    container_name: ${SERVICE_NAME}-flyway
    depends_on:
      - database
    volumes:
      - ./flyway/sql:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:mysql://${SERVICE_NAME}-database:3306/${DB_NAME}?autoreconnect=true&allowPublicKeyRetrieval=true
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_SCHEMAS: ${DB_NAME}
    command: -connectRetries=60 migrate

  application:
    build: .
    container_name: ${SERVICE_NAME}
    depends_on:
      - database
      - flyway
    env_file:
      - .env
    ports:
      - "5001:5000"
    expose:
      - "5000"
